name: Terraform Destruction

on:
  workflow_dispatch: # Manual trigger only

env:            
  AWS_REGION: us-east-1  

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production-destroy  # Ties to the protected environment
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
    
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2

     - name: Terraform Init
       run: terraform init

     - name: Terraform Destroy
       run: terraform destroy -auto-approve
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}